### ISSUE TITLE
Output column 2 and 3, values of 2 instead 0/1 for reference/variant allele

### ISSUE THREAD

**Issue by Boeinco** [vibansal/HapCUT2#11]
Hi Mr. Edge,

I am looking at some output from the HapCUT2 results and in columns 2 and 3, there is supposed to have a binary element of 0 or 1 indicating reference or variant allele. However, some lines, as shown below, contain the number 2.  Could you tell me what the number 2 means?

409     0       2       hs37d5  4503474 T       C       0:25,4:.:26:0.138       0       .       100.00

Thank you very much,
Austin

**Comment by vibansal** [comment]
'2' likely refers to the 2nd variant allele. This can occur if the VCF variant record has more than one variant allele. Let us know if this is not the case for this variant.

**Comment by Boeinco** [comment]
'2' shows up in many variants.  The VCF record has only one variant allele.  Also, we have lines such as this where chromosome columns are both 0
5       0       0       GL000219.1      73467   C       T       0:0,1:.:1:1.0   0       .       31.46.  Why would these alleles show up during phasing?

Thank you for your time,
Austin

**Comment by pjedge** [comment]
Both cases are bugs. It looks like the 'GT' field in the VCF record is '0' -- is that true? If it is, then what we're observing is undefined behaviour resulting from HapCUT2's assumption that input records are diploid. Notice that in the first case, the fields starts with "0:2....". It's misreading this as '0/2' because there's no check for the '/' or '|' character currently in parsing the VCF's individual column.

HapCUT2 is in need of more checks and a barrage of assertions in the VCF parsing code in particular, to deal with unexpected inputs. I'll try to get this started ASAP at least to catch cases like this. If you can send me a small test case with a small sample of your fragment file and a small sample of your VCF file it'll be helpful (pedge@eng.ucsd.edu), but I can also generate my own.

**Comment by Boeinco** [comment]
@pjedge Yes, you are correct, GT field with 0 is a haploid call.  hs37d5 is a concatenated decoy sequence.

**Comment by pjedge** [comment]
I pushed a fix. Haploid VCF records are now ignored by extracthairs and hapcut2, as they should be. Let me know if you have further problems.

**Comment by Boeinco** [comment]
Thanks! I probably won't get to it today but I will let you know.
