### ISSUE TITLE
Switch error estimated by HAPCUT2

### ISSUE THREAD

**Issue by yjqiu** [vibansal/HapCUT2#15]
I used --ea 1 parameter to let HAPCUT2 give estimated error rate for each phased SNPs. But the switch error rates are weird. The first SNP is 100, and all the other are 3.01.

**Comment by pjedge** [comment]
Hi,

In general the first position should be 100 since it's impossible for it to be the first SNP of a switch error. The rest of the positions have the lowest possible score -- however it might be hard to know why without knowing what the data looks like. What are the base quality scores of your fragments file (last column of fragments file)?

**Comment by yjqiu** [comment]
The base quality scores look good I think. I pasted a few lines of fragments files below. I can also send you a sample if you need.

1 K00168:103:HFHHWBBXX:5:2222:16143:33756 1 -1 -1 86 000 CBB
1 K00168:105:HFHVVBBXX:5:1106:10277:24999 1 -1 -1 85 0000 @CBD
1 K00168:103:HFHHWBBXX:6:1212:3792:36974 1 -1 -1 85 0000 ?CBC
1 K00168:104:HFJ5YBBXX:4:2119:4097:30116 1 -1 -1 85 0000 DEEC
1 K00168:103:HFHHWBBXX:2:2212:9181:41106 1 -1 -1 85 0000 @CBE
1 K00168:105:HFHVVBBXX:4:1216:10247:11935 1 -1 -1 85 0000 BB@C
1 K00168:105:HFHVVBBXX:1:2202:21024:15205 1 -1 -1 85 0000 @CAD
1 K00168:103:HFHHWBBXX:6:2113:9699:19531 1 -1 -1 85 0000 @BAD

**Comment by pjedge** [comment]
hmmm. The qualities are indeed good but it looks like all of the fragments in this sample come from the same haplotype, which is sort of unlikely to just happen by chance (roughly 1 in 256). Are you sure that the variant positions in the VCF file are properly annotated? Also please send a sample of the fragments and VCF to pedge at eng.ucsd.edu

**Comment by yjqiu** [comment]
That might because those are all trans reads. I sent you the example via email. Thanks!

**Comment by pjedge** [comment]
I'm really sorry for the delay! I've determined the issue. I forgot about this, but the switch error confidence code simply isn't implemented for HiC reads at all. In earlier versions of the code when "switch qualities" were used in a different way, there was an error message to prevent using both options at once, but it isn't currently place for error_analysis_mode.
I will make it so that in the case of HiC reads, the switch quality appears as empty.

There is a practical reason why the switch quality calculation wasn't implemented for HiC reads -- (paraphrasing from an email I sent you this afternoon, for other's benefit). The switch quality score is not intended for HiC reads at all -- its intended purpose is for detecting locations of singular switch errors in assemblies from linear reads (such as standard illumina, clones, pacbio, 10X, almost anything except HiC or similar proximity ligation tech).
Instead of single switch errors that effectively divide the haplotype block into two unrelated parts, errors in Hi-C almost always occur as small clusters of nearby variants that are switched with respect to the rest of the (very large) assembly. This is why, at sufficient coverage, the pairwise phasing accuracy between SNPs is high and uniform across all inter-variant distances for HiC (see Fig 3B in the HapCUT2 paper). Therefore the base assumption of the switch quality (that we are looking for singular weak points in the assembly) doesn't hold up. The "mismatch quality" also has its own assumption of error independence, but in my opinion it's the best choice for finding errors in HiC data (although it's likely to assign inflated qualities to variants in clusters).

We are considering implementing a specialized scoring/pruning system specifically for HiC, to root out these low-confidence clusters of variants. If there's sufficient interest we'll make it happen.

Also, I'll note that any results you may have obtained using --hic 1 --ea 1 are still perfectly valid, aside from the fact that the switch quality column is (as you already determined) is meaningless.

I can answer any other questions you may have, or feel free to close the issue if this answer is sufficient.

**Comment by yjqiu** [comment]
That answers my question. So mismatch quality is not helpful to remove low-confidence clusters of variants, is that correct?

**Comment by pjedge** [comment]
I believe mismatch quality IS still helpful with clusters, to a limited extent, but I don't have very solid data about its behaviour in this case. What I do know is that the overall mismatch accuracy improves if you increase the threshold on the mismatch quality. In theory, the mismatch quality of a variant should be more accurate (useful for pruning) the more HiC reads there are that link it to correctly phased SNVs.
example 1: a variant is in a cluster of erroneously phased variants, and it has 5 HiC reads linking it to correctly phased variants elsewhere in the block, and 1 HiC read linking it to other incorrectly phased variants also in the "error cluster". Then (in theory) the mismatch quality at this variant should be more accurate (on the low side, allowing you to prune the variant out) 
example 2: A variant is in a cluster of erroneously phased variants, and it has 1 HiC read linking it to correctly phased variants elsewhere in the block, and 5 HiC reads linking it to other incorrectly phased variants also in the "error cluster". Then the mismatch quality at this variant will be very inaccurate (abnormally high, so pruning even at a high threshold might leave this erronous variant in).

The switch quality, which is what I was saying you definitely shouldn't use, will be extremely inaccurate/unhelpful for the following reason: it will test for a single switch error at the left boundary of the error cluster, it will also test for a single switch error on the right boundary of the error cluster, but neither of these alone are "likely" at all given the data -- there are probably many, many HiC reads that jump over the cluster entirely, and link the overall haplotype together very well.

The more ideal solution is an approach that tests various sizes of dual-switch error "windows" to catch small clusters of errors. This is not currently implemented (but might be eventually).

**Comment by yjqiu** [comment]
I tried to filter by mismatch quality 100 but it is not making the result better. I now understand the problems much better, and I really look forward to the new feature!
