### ISSUE TITLE
The reads limits of HAPCUT2

### ISSUE THREAD

**Issue by yuzhang0327** [vibansal/HapCUT2#2]
Dear professor,

I have tried the HAPCUT2 with a PWK/C57BL mouse HiC data. When I used the fragment files generated by extractHAIRS, it always report errors as below:
Too many nodes allocated: 262144.
So I reduced the fragments files to just 260000 rows ( I have ~1000000 rows for the fragment file), the HAPCUT2 works well. So I wonder whether it is reasonable to split the fragment files to run HAPCUT2? If not, how can I modified the script to adjust HAPCUT2 to accept more than 1000000 reads one time?

Best,
Yu

**Comment by pjedge** [comment]
Hi Yu,

It is highly recommended you don't split up the file to run HapCUT2.
You'll just get several sub-par assembled haplotypes.
This seems like it should be a very easy fix -- I'll give it a look.

**Comment by pjedge** [comment]
@nh13 Regarding the size limit of 262144 (1 << 18) in label_node_alt, it seems like it's arbitrary and we can just increase it, no? I'm not sure if there's some subtle reason for it that has to do with khash.

**Comment by nh13** [comment]
@pjedge I don't know why the limit is there.  As long is is less than a singed integer, I think it's fine.

**Comment by yuzhang0327** [comment]
@pjedge , dear professor, if you mean we can just increase the size limit, how can I change it?

**Comment by pjedge** [comment]
@yuzhang0327 I raised the limit and I tested out on human Hi-C data where I artificially increased the number of variants. As far as I can tell it looks like it is working.

Please do open a new issue if you experience any issues with HapCUT2 on your mouse data. As far as I know this will be the first time the new HiC code has been applied to non-human Hi-C data (for instance, your original issue arose because of the increased SNP density in mice). Be sure to have the --hic option turned on in both extractHairs and HapCUT2.
