### ISSUE TITLE
Optimal number of reads

### ISSUE THREAD

**Issue by MaestSi** [vibansal/HapCUT2#23]
Dear HapCUT2 developer,
I am using MinION reads (1d^2 and 1d) to phase heterozygous SNPs starting from an Illumina VCF and a BAM file obtained mapping ONT reads against a reference (with LAST, Bowtie mem or Minimap2). I would like to know what is the optimal coverage I should use.
Since SNPs I am trying to put in phase are from a 12Kb amplicon, coverage is not an issue. Would it be better to use only the best reads (based on the Q-score) or maybe to split the reads into subsets and repeat the analysis, in order to take a decision by looking at the most frequent haplotype? Is there a particular mapper that you would advice?
Thanks in advance

**Comment by pjedge** [comment]
Hi MaestSi,

The most important thing for your case is, be sure to use the --ont 1 flag in extractHairs. This will enable realignment around the SNPs.
The second most important thing is to play close attention to the last few columns of your HapCUT2 output haplotypes and filter on mismatch/switch qualities as needed -- I'd maybe recommend the following: 

```python3 utilities/prune_haplotype.py -i <input.hap> -o <output.hap> -mq 90 -sq 30```

Other than that, I'd recommend using all of the coverage you have available and ignoring Q-scores. Is 1D^2 the same as 2D? If you have 2D reads you could perhaps leave off 1D reads since the overall error rate of those are going to be significantly higher.
