### ISSUE TITLE
Can I use ./extractHARIS with multi-thread and how to do?

### ISSUE THREAD

**Issue by jun3234** [vibansal/HapCUT2#37]
It takes one week to just generate 28 M 'fragment_file' and I don't know how long does it take.
Is there have parameters or ways to run this with multi-thread?

**Comment by pjedge** [comment]
I think it's more likely that something is going wrong, it probably shouldn't take that long... what type of reads are you using, and how many of them (or coverage)?

**Comment by jun3234** [comment]
Thank you for replying @pjedge 
I used the 'Canu' for assembling approximately 50G PacBio Sequel data and I got the output 'Canu_contig' file.
Then, the PacBio was mapped to the 'Canu_contig' and I gained bam file.
After calling snp and indel for bam file with gatk3, this step generated about 6.6G vcf file.
finally, I want to get one haplotype or two haplotypes with './extractHARIS' scripts because the genome  Heterozygosity is up to 2.27%. 
Is the ways I taked are wrong? and if that case, could you tell me how to do?

**Comment by pjedge** [comment]
ah ok. It is possible that extractHairs may take longer in the case of pacbio data, because it performs local realignments of the reads to the alleles.

However I think the problem is the variants. Did you call the SNPs and indels from the pacbio reads directly? That unfortunately won't work, you'll probably have mostly false positive variants. Not only that, but many of the genotypes will be wrong, and HapCUT2 requires very accurate variants and genotypes to work, or else you'll get very bad (meaningless) results. If you map Illumina reads to the contig and call SNPs and indels from those, this technique could possibly work. Currently, the phasing accuracy of short indels (1 and 2 bp) is pretty bad for PacBio reads, even when the genotype was accurately called with Illumina.

**Comment by jun3234** [comment]
thanks, I knew the pacbio sequencing error rate is up to 15% , so before to canu software, I had used the LoRDEC to correct the sequel raw data(fasta format, and transformed from subreads.bam), almost 200X pair-end to 100 X pacbio data.  And LoRDEC-corrected fasta  were used mapping to the 'Canu_contig', So I think there would be little effect. Am I right?
If there are no wrong with the HapCUT2 dealing with this data. I won't wait until it run over.
Thank you really!

**Comment by pjedge** [comment]
I am pretty sure that this strategy will not work at all and I would recommend against it. HapCUT2 is really only designed to work with variants with accurate genotypes called by aligning Illumina short reads to a highly accurate reference sequence, or variants of comparable quality to this.
