### ISSUE TITLE
empty result for pacbio data

### ISSUE THREAD

**Issue by yilunhuangyue** [vibansal/HapCUT2#39]
Hi, I run extractHAIRS for pacbio data with the command:
extractHAIRS --pacbio 1 --bam map.sort.bam --VCF SV.vcf --out fragment_file --ref ref.fa
but the result "fragment_file" is empty and I do not notice any error message in log file.
The pacbio data was mapped to the reference genome by ngmlr and sorted by samtools, SVs were called by sniffles, with commands:
ngmlr -t 30 -r ref.fa -q subreads.fasta -o map.sam
samtools view -bS -o map.bam map.sam
samtools sort -o map.sort.bam map.bam 
sniffles -m map.sort.bam -s 10 --genotype -v SV.vcf
Could you please help me find out where is th problem?
Thanks a lot.

**Comment by vibansal** [comment]
extracthairs works for SNV & short indels only.

**Comment by yilunhuangyue** [comment]
Hi, thank you so much for your quick reply.
I have checked my vcf file and find SVs such as INS, DEL and TRA et al, but I don't find SNVs. Maybe it is the reason why I can't get result. I not sure if I should use sniffles to call SVs, could you please recommend a tools to call SVs for pacbio read?
Thanks again.

**Comment by yilunhuangyue** [comment]
maybe I should used SNV called by illumina reads in this step?

**Comment by vibansal** [comment]
Yes.

**Comment by OceanLyu** [comment]
Hi, 
thanks for developing hapcut2!

I met the same problem when phasing varaints called by deepvariant(--model_type=PACBIO) using pacbio ccs mapped reads.  

I got an empty **fragment_file** and an empty **haplotype_output_file** and the ouput **haplotype_output_file.phased.VCF** did not contain the phasing information( still '/' instead of '|'  in GT) shown below:

NC_027278.1     10359   .       C       A,T     65.1    PASS    .       GT:GQ:DP:AD:VAF:PL:PS   1/2:3:85:0,22,63:0.258824,0.741176:62,66,24,66,0,0:.
NC_027278.1     10647   .       A       G,T     58.9    PASS    .       GT:GQ:DP:AD:VAF:PL:PS   1/2:44:80:0,38,42:0.475,0.525:58,61,45,61,0,49:.
NC_027278.1     10848   .       T       A,C     56.7    PASS    .       GT:GQ:DP:AD:VAF:PL:PS   1/2:38:81:0,42,39:0.518519,0.481481:56,52,40,52,0,42:.
NC_027278.1     10875   .       C       A,T     59.6    PASS    .       GT:GQ:DP:AD:VAF:PL:PS   1/2:40:78:0,41,37:0.525641,0.474359:59,52,41,52,0,45:.
NC_027278.1     10911   .       T       C,G     67.5    PASS    .       GT:GQ:DP:AD:VAF:PL:PS   1/2:46:80:0,42,38:0.525,0.475:67,54,53,54,0,49:.
NC_027278.1     11672   .       T       A,C     51.3    PASS    .       GT:GQ:DP:AD:VAF:PL:PS   1/2:12:74:0,33,41:0.445946,0.554054:51,45,24,45,0,12:.
NC_027278.1     12098   .       T       A,C     54.3    PASS    .       GT:GQ:DP:AD:VAF:PL:PS   1/2:19:72:1,40,31:0.555556,0.430556:54,61,18,61,0,37:.
NC_027278.1     12311   .       A       C,T     60.6    PASS    .       GT:GQ:DP:AD:VAF:PL:PS   1/2:45:69:0,39,30:0.565217,0.434783:60,53,51,53,0,48:.
NC_027278.1     12401   .       C       A,G     58.8    PASS    .       GT:GQ:DP:AD:VAF:PL:PS   1/2:36:68:0,31,36:0.455882,0.529412:58,57,41,57,0,36:.
NC_027278.1     12458   .       C       A,T     65.7    PASS    .       GT:GQ:DP:AD:VAF:PL:PS   1/2:36:69:0,38,31:0.550725,0.449275:65,75,36,75,0,44:.


Here are my codes for hapcut2:

```
extractHAIRS --pacbio 1 --bam $work_dir/mini/hifi_mini_sorted.bam \
 --VCF $work_dir/dep/gpu/manual_filtered_dep1_output.vcf --out $work_dir/phase_variants_pacbio_only/tmp/fragment_file \
 --ref $work_dir/ref/GCF_016881025.1_HiC_Itri_2_genomic.fna

HAPCUT2 --fragments $work_dir/phase_variants_pacbio_only/tmp/fragment_file \
 --VCF $work_dir/dep/gpu/manual_filtered_dep1_output.vcf --output $work_dir/phase_variants_pacbio_only/haplotype_output_file
```

**Comment by vibansal** [comment]
This is probably related to the 1/2 genotype calls in the VCF file. Hapcut2 currently filters out such variants.

**Comment by OceanLyu** [comment]
Okay, I got it. Thanks for your reply!
