### ISSUE TITLE
HAPCUT2 with --error_analysis_mode 1 can't run out with result

### ISSUE THREAD

**Issue by yuzhang0327** [vibansal/HapCUT2#4]
Dear professor,

Thanks very much for your kind help to solve the reads limit problem. However now I came with another one, when I tried to use --error_analysis_mode 1 as you stated, I can't run out with result, the program run for more than 3 days but nothing came out, while if we don't use this parameter, it took me just one hour to run out with same input file. If I don't use this parameter, the accuracy of HAPCUT2 with 70X HiC data is just about 75%, I am not sure whether this is reasonable?

Best,
Yu

**Comment by pjedge** [comment]
Hi Yu,

75% accuracy is extremely poor for any coverage of HiC data, especially 70X in mouse. Something is wrong.

I don't recall recommending the --error_analysis_mode to you earlier. Are you sure you don't mean the --hic option? If not, the slowdown is highly unusual. --error_analysis_mode should be almost as fast as normal execution. The only differences in --error_analysis_mode are (1) switch error confidence scores are computed (second to last column of output) and (2) automatic SNV pruning is turned off, letting the user prune low-quality SNVs and split blocks manually based on the scores in the last 3 columns of output. Switch error confidence scores should be very fast to compute.

I'll also note that switch error confidence scores basically won't help at all with HiC data, since Hi-C data has practically no "long switch" errors. I'd suggest just leaving --error_analysis off, and then if necessary pruning extra SNVs from your output based on the SNV confidence value of the last output column. You can also have HapCUT2 prune more SNVs automatically by increasing --threshold to 0.99, for instance (default value is 0.8).

If you are actually referring to the --hic option, this option can indeed have a significant impact both on the accuracy (more accurate) and the runtime (slower) for HiC data. If this option is too slow for you to use in practice, I have a trick I can suggest to achieve a big speed up while still improving accuracy somewhat.

**Comment by yuzhang0327** [comment]
Dear professor,

Attached is the input vcf and bam files I used for HAPCUT2. 
FYI, I have tried to remove the --qv_offset 64 --htrans_data_outfile {output.model_file} and just run HAPCUT2 as below:
HAPCUT2 --fragments fragment_fileX --vcf /data4/yu/soft/hapcut2/hapcut2-master/vcf_mm9/chrX.vcf --output output_test.hap --hic 1 

I found the accuracy will be improved to 85% and no nan appears.

Best,
Yu


Yu Zhang， PhD student
School of Life Science, Medical Science D227 
Tsinghua University, Beijing, China, 100084 
Lab: 86-10-62771496
Tel: 13311580653
Email: zhangy-11@mails.tsinghua.edu.cn
 
From: Peter Edge
Date: 2017-05-04 02:02
To: vibansal/HapCUT2
CC: yuzhang0327; Author
Subject: Re: [vibansal/HapCUT2] HAPCUT2 with --error_analysis_mode 1 can't run out with result (#4)
Hi Yu,
75% accuracy is extremely poor for any coverage of HiC data, especially 70X in mouse. Something is wrong.
I don't recall recommending the --error_analysis_mode to you earlier. Are you sure you don't mean the --hic option? If not, the slowdown is highly unusual. --error_analysis_mode should be almost as fast as normal execution. The only differences in --error_analysis_mode are (1) switch error confidence scores are computed (second to last column of output) and (2) automatic SNV pruning is turned off, letting the user prune low-quality SNVs and split blocks manually based on the scores in the last 3 columns of output. Switch error confidence scores should be very fast to compute.
I'll also note that switch error confidence scores basically won't help at all with HiC data, since Hi-C data has practically no "long switch" errors. I'd suggest just leaving --error_analysis off, and then if necessary pruning extra SNVs from your output based on the SNV confidence value of the last output column. You can also have HapCUT2 prune more SNVs automatically by increasing --threshold to 0.99, for instance (default value is 0.8).
If you are actually referring to the --hic option, this option can indeed have a significant impact both on the accuracy (more accurate) and the runtime (slower) for HiC data. If this option is too slow for you to use in practice, I have a trick I can suggest to achieve a big speed up while still improving accuracy somewhat.

**Comment by pjedge** [comment]
Hi Yu,
What is the quality value offset of your data? It should be either 64 (old illumina) or 33 (new illumina, default option), but is very important that you find out which and use '--qv_offset 64' if and only if you have the old illumina format. But this is not common nowadays.

In the other thread you said 

> 
> Dear professor,
> 
> Here is the command I used to run extractHAIRS and HapCUT2.
> extractHAIRS --HiC 1 --bam /data4/yu/soft/hapcut2/hapcut2-master/hic_separated/hic.REF_chrX.bam --VCF /data4/yu/soft/hapcut2/hapcut2-master/vcf_mm9/chrX.vcf --qvoffest 64 --out fragment_fileX &
> 
> HAPCUT2 --fragments fragment_fileX --vcf /data4/yu/soft/hapcut2/hapcut2-master/vcf_mm9/chrX.vcf --output output1.hap --hic 1 --qv_offset 64 --htrans_data_outfile {output.model_file}
> 
> Due to the bytes limitation of the files, I sent the subsamples of my input through email.
> 
> Best,
> Yu
> 

Please check that options are spelled correctly, I notice that '--qvoffest 64' is spelled incorrectly and that previously this would lead to the option being ignored in extractHairs.

I just pushed a change so that ExtractHairs and HapCUT check the validity of input options more stringently.

**Comment by pjedge** [comment]
Just checking but is this issue resolved?
