### ISSUE TITLE
Running HAPCUT2 after Canu

### ISSUE THREAD

**Issue by psur9757** [vibansal/HapCUT2#52]
I have created a collapsed assembly using Canu (https://github.com/marbl/canu) and now would like to run HAPCUT2 for phasing. Is there a recipe or code for this. Thank you.

> From Canu
> Smash haplotypes together and then do phasing using another approach (like HapCUT2 or whatshap or others).

Best Regards,
Priyanka

**Comment by pjedge** [comment]
Hi Priyanka,

we don't officially support the use case of phasing assemblies (only because I have not seen published works demonstrating that it is accurate). But, it seems like it should work in theory, and other users seem to have done it. What sort of data do you have available?

**Comment by psur9757** [comment]
Hi Peter,

We have PacBio reads with about 160x coverage. I have created a de novo assembly using Canu. Since the authors of Canu recommended it, I thought this must be done. If you could provide some guidance, it would be most helpful. Thank you.

Best,
Priyanka




Priyanka Surana | Postdoctoral Research Associate
Plant Breeding Institute | The University of Sydney
Room A2-4, 107 Cobbitty Rd, Cobbitty, NSW 2570
+61 2 9351 8825 (o) | +61 481 785 312 (m)

**Comment by pjedge** [comment]
Hi Priyanka,
The biggest challenge in this case will be determining the heterozygous sites and accurately genotyping them. Normally, with the currently available techniques, this requires short reads.

However, the general technique would look like this:
1. convert your assembly into fasta format (it should be haploid / squashed ploidy)
2. align the PacBio reads to the fasta-format assembly (BLASR/minimap2).
3. obtain an accurate set of heterozygous variants in VCF format (if you had short reads, you would align the short reads to the assembly and then call variants with, for example, GATK)
4. proceed as normal with extractHairs + HapCUT (use --pacbio 1 option when running extractHairs)

Step 3 will be a challenge for you. Regardless of coverage, the genotypes at heterozygous sites will be extremely inaccurate using PacBio reads becuase there aren't very good methods for this.

**Comment by psur9757** [comment]
Hi Peter,

I can get Illumina reads for both DNA and RNA as well. The haplophasing is important to us so let me know what is the ideal method and I will get the required data.

Best,
Priyanka

**Comment by pjedge** [comment]
Hi Priyanka,
If you have WGS (genomic) short reads at reasonable coverage (30x minimum) I would expect the steps I described to work. Be sure to filter the variants (step 3) using best practices so that the VCF being used with extractHairs/HapCUT2 only contains highly accurate variants that you're confident are real. Note that in regions where the assembly is inaccurate, or the reads are mapped inaccurately, the haplotypes will also be bad. And a final note: you'll undoubtedly find heterozygous short indels along with SNVs, using the short reads. Be aware that if you try to phase these (with the --indels 1 option in extractHAIRS, along with the --pacbio 1 option), it can be done but the accuracy of the very small indels (1-2 bp) may not be very good. These small indels are hard to allelotype on long reads, which then hurts phasing accuracy. However, with such high coverage it may be alright.

**Comment by pjedge** [comment]
Correct. The idea is that you're using the haploid assembly as the "reference genome".

**Comment by pjedge** [comment]
Probably. You should take any steps to make sure the assembly is as accurate of a haploid assembly as possible. I can't say for certain since I've never done this. If anyone has done this with good success, please share here.

**Comment by psur9757** [comment]
I used Canu to assemble both the default way and the smashed ploidy way. The smashed ploidy way gave more unitigs than the default. Canu authors explained it here: https://github.com/marbl/canu/issues/1151. 

So going back to the steps you recommended, should I use just the contigs.fasta file or both contigs.fa and unitigs.fa?
