### ISSUE TITLE
There No Exception and errors raised, but no output file

### ISSUE THREAD

**Issue by jun3234** [vibansal/HapCUT2#57]
There is 100X hic was generated to 'bam' with bwa mem, and 300X illumina pair-end data was generated to vcf file. 
I want to run hapcut2 multitask by chromosome, because it's take too much time to run this work with one thread, five days have been used, but there no any output. 

my flow as follows:
## step 1,  split bam and vcf by chromosome
for id in `cat Chr.id`;do
samtools view -b -h hic.sorted.bam $id > ${id}.bam &
done
for id in `cat Chr.id`;do
python /home/smrtanalysis/tools/python_scripts/vcf.py vcf_split FZX_BGI_illumina.vcf -chr $id > ${id}.vcf &
done
## step 2,  get fragment
for id in `cat Chr.id`;do
extractHAIRS --hic 1 --bam ${id}.bam --VCF ${id}.vcf --indels 1 --ref Hap_alt.FINAL.Chr1-15.fasta --out ${id}.hapcut.fragment &
done
## step 3,  to haplotype, but failed
for id in `cat Chr.id`;do
HAPCUT2 --hic 1 --fragments ${id}.hapcut.fragment --vcf ${id}.vcf --output ${id}.hapcut.haplotype > ${id}.hap.log &
done

Chr.id file like that:
[smrtanalysis@localhost split_multask]$ head Chr.id
HiC_scaffold_1
HiC_scaffold_3
HiC_scaffold_4
HiC_scaffold_6
HiC_scaffold_7
HiC_scaffold_8

fragment file like that:
[smrtanalysis@localhost split_multask]$ head HiC_scaffold_7.hapcut.fragment
1 ST-E00142:598:HHVJNCCXY:1:1108:17563:10363 1 -1 -1 12 010001 ??????
1 ST-E00144:637:HCVNFCCXY:3:1120:5629:39159 1 -1 -1 13 0000000000 >>>>>>>>>>
1 ST-E00144:637:HCVNFCCXY:3:1204:5781:59745 1 -1 -1 13 0000000 <??????
1 ST-E00251:459:HFJHWCCXY:7:2213:24058:46578 1 -1 -1 14 000 JJJ
1 ST-E00251:459:HFJHWCCXY:7:2213:23967:46630 1 -1 -1 14 00 JJ

but when I executed the commond:
for id in `cat Chr.id`;do
HAPCUT2 --hic 1 --fragments ${id}.hapcut.fragment --vcf ${id}.vcf --output ${id}.hapcut.haplotype > ${id}.hap.log &
done
 No error raised, and No output but log file containing info like that:
[2018:12:31 08:37:49] fragment file: HiC_scaffold_7.hapcut.fragment
[2018:12:31 08:37:49] variantfile (VCF format):HiC_scaffold_7.vcf
[2018:12:31 08:37:49] haplotypes will be output to file: HiC_scaffold_7.hapcut.haplotype
[2018:12:31 08:37:49] solution convergence cutoff: 5
[2018:12:31 08:37:49] QVoffset: 33

[2018:12:31 08:37:49] Calling Max-Likelihood-Cut based haplotype assembly algorithm
[2018:12:31 08:38:19] read 721407 variants from HiC_scaffold_7.vcf file
[2018:12:31 08:38:40] fragments 8467289 snps 721407 component(blocks) 6393
[2018:12:31 08:38:49] processed fragment file and variant file: fragments 8467289 variants 721407

Could you help me to solve this problem?  there no  HiC_scaffold_7.hapcut.haplotype file.
look forward to your reply.

**Comment by jun3234** [comment]
Yes, every single VCF file has > 700,000 variants:
HiC_scaffold_1     1059205
HiC_scaffold_3     991090
HiC_scaffold_4     985716
HiC_scaffold_6     830019
HiC_scaffold_7     721407
HiC_scaffold_8     1147585
HiC_scaffold_9     826058
HiC_scaffold_10    557369
HiC_scaffold_11    882118
HiC_scaffold_12    1023851
HiC_scaffold_14    706283
HiC_scaffold_16    1654251
HiC_scaffold_18    1276596
HiC_scaffold_19    523647
HiC_scaffold_13_2  965394
Now, I test the VCF file(first 1000 variants).
Thanks.

**Comment by pjedge** [comment]
I think it would take an impractically long time. Some thoughts/ideas:

(1) One thing that you could do to improve the runtime would be to run HapCUT with the option "--nf 1" and remove the --hic 1 option. HapCUT2 can take much longer to run (maybe 5-20 times) when it is modeling trans errors using multiple assembly iterations. This setting will allow the hic formatted input but will not model the trans errors. If the overall sequence coverage is very good then the accuracy should be decent anyway.

(2) If option 1 leads to a significant improvement in runtime, but you think that htrans errors might be affecting your results in a meaningful way, there are other things that can be done to try to account for them -- HapCUT2 has a hidden option to explicitly provide an htrans error model. I'd consider this to be an advanced solution and it makes assumptions about the rate of trans errors.

(3) HapCUT2 scales very well with increased sequencing coverage/number of reads but scales more poorly with the number of variants. So you could subsample the reads to improve the runtime but it probably isn't worth it. But if you broke the VCF into chunks and process them separately (starting from the extractHAIRs), you might improve the runtime significantly (an improvement that is better than linear in the number of chunks). The problem with this approach is that you would need to recombine the separate VCF chunks using Hi-C reads that span across them, or by having the chunks overlap and matching up the phase of the overlapping regions.

Anyway, (1) is a very easy solution, (2) is a more complicated version of it that requires you to make a hard assumption about what the trans error rates are, and (3) is complicated because it would require some scripting or custom code to recombine separate haplotype chunks.

**Comment by jun3234** [comment]
Very thankful,  you have offered three great methods to solve this problem especially the third one. 
I master python and shell language a little and I will try it .
@pjedge, many thanks, ~
