### ISSUE TITLE
Invalid SNV confidence score on HAPCUT2 after extractHAIRS w/o filtering

### ISSUE THREAD

**Issue by LillianZ** [vibansal/HapCUT2#63]
Trying to run HAPCUT2 when the options "--mbq 0 --mmq 0 --maxIS 1000000000 --minIS 0" are used during the extractHAIRS phase causes Invalid SNV confidence score

Works without the options; and works on HAPCUT both with and without those options

**Comment by pjedge** [comment]
This is happening because --mbq 0 allows bases with quality encoding of "!" which means they have a "100% probability of error". This causes some likelihoods to get zeroed out and breaks the model. This would probably result in bad haplotypes and it crashes when trying to print the haplotype output because the SNV confidence score is "NaN". To remedy this, I've simply added a check (and error message) so that the --mbq flag is at least 4 (probability of error is ~40%).
