### ISSUE TITLE
MEC score

### ISSUE THREAD

**Issue by smajidian** [vibansal/HapCUT2#79]
Dear Hapcut team
The format of block header is mentioned on the first page of Github as 
```
BLOCK: offset: <SNV offset> len: <SNV span of block> phased: <# SNVs phased> SPAN: <base pair span of block> fragments <# of fragments in block>
```
But in the output file the header is
```
BLOCK: offset: 13988 len: 171 phased: 169 SPAN: 195268 MECscore 252.05 fragments 2334

..

BLOCK: offset: 14324 len: 10 phased: 10 SPAN: 17700 MECscore 10.29 fragments 128

```
The definition of MEC score is not clear to me.  I need to calculate the MEC score in my project. As far as I understand from the Hapcut1 paper, it should be an integer but here it is a rational number.  I'm wondering how you calculated it? maybe you divide the MEC by haplotype length?  But  10.29*10 is not an integer!

Thanks you in advance.

**Comment by smajidian** [comment]
Dear @pjedge 
I will thankful if you can help me on this.

**Comment by pjedge** [comment]
Hi, I am not using a computer much due to an injury, but I can dictate a
brief response. Based on memory, I think that the calculation for MEC score
output by HapCUT2 sums penalties that aren't binary, but are rather scaled
based on the quality values for the alleles. This is a vestige of the
stepping stone from HapCUT1 to HapCUT2, which used the same MEC based
algorithm but scaled penalties using the quality scores.

I think I have some simple python based code that can calculate MEC
correctly, but it's sort of scattered and it won't be easy to share until I
can use a computer.

**Comment by smajidian** [comment]
Thanks a lot. I hope you get well soon ;)

**Comment by smajidian** [comment]
Dear Peter
I hope you have recovered well.  
I found your python function compute_mec in  [error_rates.py](https://github.com/vibansal/HapCUT2/blob/c2e66089bc8bb789e00db0b43f97bdf08e97c229/reproduce_hapcut2_paper/error_rates.py). It seems that it's for one haplotype block. I tried to generalize it and uploaded it in [calculate_mec.py](https://github.com/smajidian/Hap10/blob/master/utilities/calculate_mec.py). I'm done with this part of my project. Thanks anyway.
