### ISSUE TITLE
Suggestion to make a new release

### ISSUE THREAD

**Issue by marcelm** [vibansal/HapCUT2#86]
Hi, would it be possible to tag a new version of HapCUT2? As I mentioned in #30, I’m trying to package HapCUT2 for Bioconda (see bioconda/bioconda-recipes#18350). However, I’m getting "munmap_chunk(): invalid pointer" messages from version 1.1, which don’t occur with the version from the master branch. I am guessing this is due to 22d3451e5a0a2ed2852424c1e08c08d11a9cb86d.

I can include a patch with the recipe that fixes this (based on the commit above), but it would be nicer if simply a new version was available that includes the fix.

If you could even merge #85 before tagging a new release, that would be even better.

**Comment by pjedge** [comment]
thank you! I was working on a new front end for the software written in Python, and i was hoping to finish that before packaging the software for bioconda. i didn't finish it, so i delayed bioconda as well. I will merge your changes, so that you can package it. going forward, I can try to help keep the package current, and hopefully the front end will be production ready soon as well.
